name: subscription_tracker
description: Clean, offline-first Subscription Tracker mobile app with local notifications.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  equatable: ^2.0.5
  fluentui_icons: ^1.0.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.2.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  flutter_timezone: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.1.0
  image_cropper: ^8.0.0
  image_picker: ^1.2.1
  path_provider: ^2.1.2
  intl: ^0.20.2
  logger: ^2.0.0
  material_design_icons_flutter: ^7.0.7296
  permission_handler: ^11.0.0
  riverpod: ^2.4.0
  timezone: ^0.9.2
  uuid: ^4.0.0

dev_dependencies:
  build_runner: ^2.4.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
